# Generated by Django 5.2.3 on 2025-07-01 13:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagne', '0001_initial'),
        ('scenari', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMinaccia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campagna', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='campagne.campagna')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scenari.scenario', verbose_name='Scenario di riferimento')),
            ],
            options={
                'verbose_name': 'historical Minaccia',
                'verbose_name_plural': 'historical Minacce',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Minaccia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('campagna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minacce', to='campagne.campagna')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenari.scenario', verbose_name='Scenario di riferimento')),
            ],
            options={
                'verbose_name': 'Minaccia',
                'verbose_name_plural': 'Minacce',
                'unique_together': {('descrizione', 'campagna')},
            },
        ),
    ]
