# Generated by Django 5.2.3 on 2025-07-01 13:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(verbose_name='Anno')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('data_inizio', models.DateField(verbose_name='Data inizio campagna')),
                ('data_fine', models.DateField(verbose_name='Data fine campagna')),
                ('status', models.CharField(choices=[('open', 'Aperta'), ('close', 'Chiusa')], default='open', max_length=10, verbose_name='Stato')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCampagna',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(verbose_name='Anno')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('data_inizio', models.DateField(verbose_name='Data inizio campagna')),
                ('data_fine', models.DateField(verbose_name='Data fine campagna')),
                ('status', models.CharField(choices=[('open', 'Aperta'), ('close', 'Chiusa')], default='open', max_length=10, verbose_name='Stato')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical campagna',
                'verbose_name_plural': 'historical campagnas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
