# Generated by Django 5.2.3 on 2025-07-01 13:55

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalControllo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('tipologia_controllo', models.CharField(choices=[('Documentale', 'Documentale'), ('Tecnologico', 'Tecnologico'), ('Processo', 'Processo'), ('Misurazione base', 'Misurazione base'), ('Misurazione intermedia', 'Misurazione intermedia'), ('Misurazione avanzata', 'Misurazione avanzata')], max_length=50, verbose_name='Tipologia')),
                ('peso_controllo', models.FloatField(editable=False, verbose_name='Peso')),
                ('categoria_controllo', models.CharField(choices=[('preventive', 'Preventive'), ('detective', 'Detective')], max_length=20, verbose_name='Categoria')),
                ('macroambito', models.CharField(blank=True, max_length=255, verbose_name='Macroambito di controllo')),
                ('riferimento_best_practies', models.CharField(blank=True, max_length=255, verbose_name='Riferimento Best Practices')),
                ('riferimento_normativo', models.CharField(blank=True, max_length=255, verbose_name='Riferimento Normativo')),
                ('riferimento_processo_ITIL', models.CharField(blank=True, max_length=255, verbose_name='Riferimento Processo ITIL')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Controllo',
                'verbose_name_plural': 'historical Controlli',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Controllo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('tipologia_controllo', models.CharField(choices=[('Documentale', 'Documentale'), ('Tecnologico', 'Tecnologico'), ('Processo', 'Processo'), ('Misurazione base', 'Misurazione base'), ('Misurazione intermedia', 'Misurazione intermedia'), ('Misurazione avanzata', 'Misurazione avanzata')], max_length=50, verbose_name='Tipologia')),
                ('peso_controllo', models.FloatField(editable=False, verbose_name='Peso')),
                ('categoria_controllo', models.CharField(choices=[('preventive', 'Preventive'), ('detective', 'Detective')], max_length=20, verbose_name='Categoria')),
                ('macroambito', models.CharField(blank=True, max_length=255, verbose_name='Macroambito di controllo')),
                ('riferimento_best_practies', models.CharField(blank=True, max_length=255, verbose_name='Riferimento Best Practices')),
                ('riferimento_normativo', models.CharField(blank=True, max_length=255, verbose_name='Riferimento Normativo')),
                ('riferimento_processo_ITIL', models.CharField(blank=True, max_length=255, verbose_name='Riferimento Processo ITIL')),
                ('campagna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlli', to='campagne.campagna')),
            ],
            options={
                'verbose_name': 'Controllo',
                'verbose_name_plural': 'Controlli',
            },
        ),
    ]
