# Generated by Django 5.2.3 on 2025-07-01 13:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagne', '0001_initial'),
        ('controlli', '0001_initial'),
        ('minacce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('is_base', models.BooleanField(default=True, editable=False, help_text="Indica se l'elemento è di base o derivato da altri.", verbose_name='Di Base')),
                ('is_enabled', models.BooleanField(default=False, help_text="Indica se l'elemento è utilizzabile nelle catene tecnologiche.", verbose_name='Abilitato')),
                ('campagna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elementtypes', to='campagne.campagna')),
                ('cloned_from', models.ForeignKey(blank=True, help_text="Riferimento all'ElementType master da cui questo è stato clonato.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='elementtypes.elementtype', verbose_name='Clonato da (Master)')),
                ('component_element_types', models.ManyToManyField(blank=True, help_text='Selezionare uno o più Element Type per creare un tipo derivato. Lasciare vuoto per un tipo base.', to='elementtypes.elementtype', verbose_name='Elementi componenti (per tipi derivati)')),
                ('minacce', models.ManyToManyField(blank=True, to='minacce.minaccia', verbose_name='Minacce Applicabili')),
            ],
            options={
                'verbose_name': 'Element Type',
                'verbose_name_plural': 'Element Types',
                'unique_together': {('nome', 'campagna')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalElementType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('is_base', models.BooleanField(default=True, editable=False, help_text="Indica se l'elemento è di base o derivato da altri.", verbose_name='Di Base')),
                ('is_enabled', models.BooleanField(default=False, help_text="Indica se l'elemento è utilizzabile nelle catene tecnologiche.", verbose_name='Abilitato')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campagna', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='campagne.campagna')),
                ('cloned_from', models.ForeignKey(blank=True, db_constraint=False, help_text="Riferimento all'ElementType master da cui questo è stato clonato.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elementtypes.elementtype', verbose_name='Clonato da (Master)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Element Type',
                'verbose_name_plural': 'historical Element Types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ValoreElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.FloatField(verbose_name='Valore')),
                ('controllo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlli.controllo')),
                ('elementtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valori_matrice', to='elementtypes.elementtype')),
                ('minaccia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minacce.minaccia')),
            ],
            options={
                'verbose_name': 'Valore Matrice Element Type',
                'verbose_name_plural': 'Valori Matrice Element Type',
                'unique_together': {('elementtype', 'minaccia', 'controllo')},
            },
        ),
    ]
